version: 0.2

phases:
  build:
    commands:
      - echo "Deploying using SSM"
      - aws ssm send-command \
          --instance-ids "i-0eab9b2ac2c18690b" \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy app" \
          --parameters commands=["cd /home/ubuntu/app","npm install","pm2 restart app || pm2 start app.js"] \
          --region ap-south-1
